version: '3'
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/data
    environment:
      - DB_PATH=/data/files.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
